import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load Geist Sans font
const geistSans = Geist({
  subsets: ["latin"],
  weight: ["400", "700"], // optional weights
});

// Load Geist Mono font
const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "700"], // optional weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout wraps all pages
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Apply fonts globally via className */}
      <body className={`${geistSans.className} ${geistMono.className}`}>
        {children}
      </body>
    </html>
  );
}