import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load Geist Sans font
const geistSans = Geist({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Load Geist Mono font
const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout wraps all pages
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className}`}>
        <main style={{ width: "100%", height: "100%" }}>
          {children}
        </main>
      </body>
    </html>
  );
}